name: n_triples_parser
description: N-Triples parser for Dart
version: 0.1.0
homepage: https://github.com/amin-ahmadi-com/n_triples_parser

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  characters: ^1.2.1
  tuple: ^2.0.1

dev_dependencies:
  test: ^1.22.1
